[package]
name = "blog_os"
version = "0.1.0"
authors = ["ker <ker@qlik.com>"]
edition = "2018"

[dependencies]
bootloader_precompiled = "0.2.0"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[package.metadata.bootimage]
default-target = "x86_64-blog_os.json"